"""create bill tables

Revision ID: 21a38ea0e61a
Revises: 
Create Date: 2026-03-15 20:36:04.893625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a38ea0e61a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=10), nullable=False),
    sa.Column('bill_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('latest_action', sa.Text(), nullable=True),
    sa.Column('latest_action_date', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('ingest_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline', sa.String(length=50), nullable=False),
    sa.Column('last_processed', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('party', sa.String(length=5), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('bioguide_id')
    )
    op.create_table('bill_to_cosponsor',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('bioguide_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['bioguide_id'], ['sponsors.bioguide_id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'bioguide_id')
    )
    op.create_table('bill_to_sponsor',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('bioguide_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['bioguide_id'], ['sponsors.bioguide_id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'bioguide_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_to_sponsor')
    op.drop_table('bill_to_cosponsor')
    op.drop_table('sponsors')
    op.drop_table('parse_failures')
    op.drop_table('ingest_checkpoints')
    op.drop_table('bills')
    # ### end Alembic commands ###
