"""enrich bill schema with chamber, introduced_date, bill_url, and subjects

Revision ID: 600c0985b338
Revises: b2c3d4e5f6a7
Create Date: 2026-04-26 18:09:02.988790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600c0985b338'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislative_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_subject_name')
    )
    op.create_table('bill_subjects',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['legislative_subjects.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'subject_id')
    )
    op.add_column('bills', sa.Column('introduced_date', sa.String(length=20), nullable=True))
    op.add_column('bills', sa.Column('chamber', sa.String(length=10), nullable=True))
    op.add_column('bills', sa.Column('bill_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'bill_url')
    op.drop_column('bills', 'chamber')
    op.drop_column('bills', 'introduced_date')
    op.drop_table('bill_subjects')
    op.drop_table('legislative_subjects')
    # ### end Alembic commands ###
