"""add text_url to bills

Revision ID: a9a1e0d64a15
Revises: 600c0985b338
Create Date: 2026-04-27 12:45:00.083728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a1e0d64a15'
down_revision: Union[str, None] = '600c0985b338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('text_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'text_url')
    # ### end Alembic commands ###
